### ISSUE TITLE
Apply triage rules to issues when we remove triage/needs-triage label

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-github-bot#43]
When the automatic triaging fails, we add the `triage/needs-triage` label.

We end up adding `area/...` labels manually and what would be cool would be the following:
- issue marked with `triage/needs-triage`
- I add a couple of `area/...` labels
- I then remove the `triage/needs-triage` label (this would need to be done as a separate step to be sure operations are properly ordered)
- and the bot could then ping people based on the `area/...` labels that were manually added based on the triage config file.

**Comment by saumya1singh** [comment]
Ok so when automatic triaging fails, `quarkus-bot` add the label `triage/needs-triage`, then we manually add the `area/...` label and remove `triage/needs-triage`. 

So here you want once the `area/..` label is manually added, the `quarkus-bot` should ping people around that area i.e **if the area label is present and the issue is not triaged then CC the devs. Right :)?** 
I am on it!
