### ISSUE TITLE
Publish results of finished jobs before the workflow finished

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#99]
Currently, the bot seems to publish the results after the workflow has finished.

Sometimes, there are only a few job still running but one or more jobs have failed.
It would be nice if the bot would publish those results before the workflow has finished (as soon as a job failed), if that's even possible.
For this, I guess the bot would have to be able to overwrite the comment multiple times.

**Comment by gsmet** [comment]
I don't think this is really possible or even something we would like. I think it's nice to have a comment/notification with the full status rather than a notification with a partial one.

As for possible, the artifacts are published at the end of the workflow so they won't be accessible until the workflow is finished. Also we would have to poll the workflow status as there's no event for a finished job, just for the completed workflow.

**Comment by famod** [comment]
Ok, makes sense. Way too much effort and too many uncertainties for not that much benefit.
